### ISSUE TITLE
Version 13

### ISSUE THREAD

**Issue by satyendranegi** [learnsmartcoding/angular-for-beginners#8]
![IMG_20240930_161309.jpg](https://github.com/user-attachments/assets/75de2e32-390a-4365-959a-5298627915b4)

**Comment by learnsmartcoding** [comment]
Hello,

What does { useHash: true } do?
When { useHash: true } is set, Angular uses the "hash-based" routing strategy. This means the URLs will contain a # symbol (hash fragment) after the domain, for example: https://example.com/#/home

Use { useHash: true }: If your server cannot handle path-based routing or you need a simple setup with no server configuration.
Avoid { useHash: true }: If you can configure your web server to support path-based routing, especially if SEO is a concern.

**Comment by satyendranegi** [comment]
You're right 👍.
Great for those without SEO project here.


Thanks buddy..
